# Generated by Django 5.0.4 on 2024-04-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discounts',
            field=models.ManyToManyField(blank=True, to='products.discountproducts'),
        ),
    ]
