# Generated by Django 5.0.4 on 2024-04-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='taken_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
