# Generated by Django 5.0.4 on 2024-04-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_products_category_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountproducts',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
