# Generated by Django 5.0.4 on 2024-04-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_discountproducts_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='discounts',
        ),
    ]
