# Generated by Django 5.0.4 on 2024-04-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_products_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountproducts',
            name='image',
            field=models.ImageField(default=1, upload_to='products/discount'),
            preserve_default=False,
        ),
    ]
